import jsPDF from 'jspdf';

export const generateReportPDF = (
  title: string,
  sections: { heading: string; content: string | string[] }[],
  metadata?: { label: string; value: string }[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = 20;

  // Title
  doc.setFontSize(24);
  doc.setTextColor(139, 92, 246); // Primary purple
  doc.text(title, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Metadata line
  if (metadata && metadata.length > 0) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const metaText = metadata.map(m => `${m.label}: ${m.value}`).join(' • ');
    doc.text(metaText, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;
  }

  // Divider
  doc.setDrawColor(139, 92, 246);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Sections
  sections.forEach((section) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Section heading
    doc.setFontSize(14);
    doc.setTextColor(139, 92, 246);
    doc.text(section.heading, margin, yPosition);
    yPosition += 8;

    // Section content
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);

    if (Array.isArray(section.content)) {
      section.content.forEach((item) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const bulletText = `• ${item}`;
        const lines = doc.splitTextToSize(bulletText, contentWidth);
        doc.text(lines, margin + 5, yPosition);
        yPosition += lines.length * 6 + 3;
      });
    } else {
      const lines = doc.splitTextToSize(section.content, contentWidth);
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });
    }

    yPosition += 10;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Cosmic Insights • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      285,
      { align: 'center' }
    );
  }

  return doc;
};

export const downloadPDF = (doc: jsPDF, filename: string) => {
  doc.save(`${filename}.pdf`);
};
